---
- name: Install tree on Ubuntu servers
  hosts: ubuntu
  tasks:
    - name: Install tree using apt
      apt:
        name: tree
        state: present
        update_cache: yes
- name: Install tree on Redhat servers
  hosts: redhat
  tasks:
    - name: Install tree using yum
      yum:
        name: tree
        state: present
        update_cache: yes
...
