---
- name: Check if the file is executable and if it is delete it
  hosts: all
  tasks:
    - name: Check for f1 file
      stat:
        path: /tmp/file1
      register: a
    - name: Display output of the above module
      debug:
        var: a
    - name: Delete if the file is executable
      file:
        name: /tmp/file1
        state: absent
      when: a.stat.executable == true

